import type { HotkeyBinding } from "./types"

export const DEFAULT_HOTKEYS: HotkeyBinding[] = [
	{
		id: "file.new",
		label: "New Note",
		category: "File",
		defaultKeys: "mod+n",
		keys: "mod+n",
		enabled: true,
	},
	{
		id: "file.close-tab",
		label: "Close Tab",
		category: "File",
		defaultKeys: "mod+w",
		keys: "mod+w",
		enabled: true,
	},
	{
		id: "file.reopen-closed",
		label: "Reopen Closed Tab",
		category: "File",
		defaultKeys: "mod+shift+t",
		keys: "mod+shift+t",
		enabled: true,
	},
	{
		id: "navigate.quick-finder",
		label: "Quick Finder",
		category: "Navigate",
		defaultKeys: "mod+o",
		keys: "mod+o",
		enabled: true,
	},
	{
		id: "navigate.command-palette",
		label: "Command Palette",
		category: "Navigate",
		defaultKeys: "mod+p",
		keys: "mod+p",
		enabled: true,
	},
	{
		id: "navigate.mru-next",
		label: "Next Tab (MRU)",
		category: "Navigate",
		defaultKeys: "mod+Tab",
		keys: "mod+Tab",
		enabled: true,
	},
	{
		id: "navigate.mru-prev",
		label: "Previous Tab (MRU)",
		category: "Navigate",
		defaultKeys: "mod+shift+Tab",
		keys: "mod+shift+Tab",
		enabled: true,
	},
	{
		id: "navigate.tab-1",
		label: "Go to Tab 1",
		category: "Navigate",
		defaultKeys: "mod+1",
		keys: "mod+1",
		enabled: true,
	},
	{
		id: "navigate.tab-2",
		label: "Go to Tab 2",
		category: "Navigate",
		defaultKeys: "mod+2",
		keys: "mod+2",
		enabled: true,
	},
	{
		id: "navigate.tab-3",
		label: "Go to Tab 3",
		category: "Navigate",
		defaultKeys: "mod+3",
		keys: "mod+3",
		enabled: true,
	},
	{
		id: "navigate.tab-4",
		label: "Go to Tab 4",
		category: "Navigate",
		defaultKeys: "mod+4",
		keys: "mod+4",
		enabled: true,
	},
	{
		id: "navigate.tab-5",
		label: "Go to Tab 5",
		category: "Navigate",
		defaultKeys: "mod+5",
		keys: "mod+5",
		enabled: true,
	},
	{
		id: "navigate.tab-6",
		label: "Go to Tab 6",
		category: "Navigate",
		defaultKeys: "mod+6",
		keys: "mod+6",
		enabled: true,
	},
	{
		id: "navigate.tab-7",
		label: "Go to Tab 7",
		category: "Navigate",
		defaultKeys: "mod+7",
		keys: "mod+7",
		enabled: true,
	},
	{
		id: "navigate.tab-8",
		label: "Go to Tab 8",
		category: "Navigate",
		defaultKeys: "mod+8",
		keys: "mod+8",
		enabled: true,
	},
	{
		id: "navigate.tab-9",
		label: "Go to Tab 9",
		category: "Navigate",
		defaultKeys: "mod+9",
		keys: "mod+9",
		enabled: true,
	},
	{
		id: "view.toggle-sidebar",
		label: "Toggle Sidebar",
		category: "View",
		defaultKeys: "mod+[",
		keys: "mod+[",
		enabled: true,
	},
	{
		id: "view.toggle-theme",
		label: "Toggle Theme",
		category: "View",
		defaultKeys: "mod+shift+d",
		keys: "mod+shift+d",
		enabled: true,
	},
	{
		id: "editor.toggle-mode",
		label: "Toggle Editor Mode",
		category: "Editor",
		defaultKeys: "mod+e",
		keys: "mod+e",
		enabled: true,
	},
	{
		id: "editor.find",
		label: "Find in File",
		category: "Editor",
		defaultKeys: "mod+f",
		keys: "mod+f",
		enabled: true,
	},
	{
		id: "editor.find-in-vault",
		label: "Find in Vault",
		category: "Editor",
		defaultKeys: "mod+shift+f",
		keys: "mod+shift+f",
		enabled: true,
	},
	{
		id: "app.settings",
		label: "Open Settings",
		category: "App",
		defaultKeys: "mod+,",
		keys: "mod+,",
		enabled: true,
	},
	{
		id: "tags.toggle-picker",
		label: "Tag Picker",
		category: "Tags",
		defaultKeys: "mod+t",
		keys: "mod+t",
		enabled: true,
	},
	{
		id: "quickfinder.create",
		label: "Create New Note",
		category: "QuickFinder",
		defaultKeys: "shift+Enter",
		keys: "shift+Enter",
		enabled: true,
	},
	{
		id: "quickfinder.open-new-tab",
		label: "Open in New Tab",
		category: "QuickFinder",
		defaultKeys: "mod+Enter",
		keys: "mod+Enter",
		enabled: true,
	},
	{
		id: "quickfinder.open-split",
		label: "Open in Split",
		category: "QuickFinder",
		defaultKeys: "mod+shift+Enter",
		keys: "mod+shift+Enter",
		enabled: true,
	},
	{
		id: "navigate.daily-note",
		label: "Open Daily Note",
		category: "Navigate",
		defaultKeys: "mod+d",
		keys: "mod+d",
		enabled: true,
	},
	{
		id: "format.bold",
		label: "Bold",
		category: "Format",
		defaultKeys: "mod+b",
		keys: "mod+b",
		enabled: true,
	},
	{
		id: "format.italic",
		label: "Italic",
		category: "Format",
		defaultKeys: "mod+i",
		keys: "mod+i",
		enabled: true,
	},
	{
		id: "format.strikethrough",
		label: "Strikethrough",
		category: "Format",
		defaultKeys: "mod+shift+x",
		keys: "mod+shift+x",
		enabled: true,
	},
	{
		id: "format.inline-code",
		label: "Inline Code",
		category: "Format",
		defaultKeys: "mod+`",
		keys: "mod+`",
		enabled: true,
	},
	{
		id: "format.link",
		label: "Insert Link",
		category: "Format",
		defaultKeys: "mod+k",
		keys: "mod+k",
		enabled: true,
	},
	{
		id: "format.image",
		label: "Insert Image",
		category: "Format",
		defaultKeys: "mod+shift+k",
		keys: "mod+shift+k",
		enabled: true,
	},
	{
		id: "format.heading-1",
		label: "Heading 1",
		category: "Format",
		defaultKeys: "mod+alt+1",
		keys: "mod+alt+1",
		enabled: true,
	},
	{
		id: "format.heading-2",
		label: "Heading 2",
		category: "Format",
		defaultKeys: "mod+alt+2",
		keys: "mod+alt+2",
		enabled: true,
	},
	{
		id: "format.heading-3",
		label: "Heading 3",
		category: "Format",
		defaultKeys: "mod+alt+3",
		keys: "mod+alt+3",
		enabled: true,
	},
	{
		id: "format.blockquote",
		label: "Blockquote",
		category: "Format",
		defaultKeys: "mod+shift+.",
		keys: "mod+shift+.",
		enabled: true,
	},
	{
		id: "format.code-block",
		label: "Code Block",
		category: "Format",
		defaultKeys: "mod+shift+`",
		keys: "mod+shift+`",
		enabled: true,
	},
	{
		id: "format.task-list",
		label: "Task List / Toggle Done",
		category: "Format",
		defaultKeys: "mod+l",
		keys: "mod+l",
		enabled: true,
	},
	{
		id: "format.unordered-list",
		label: "Unordered List",
		category: "Format",
		defaultKeys: "mod+shift+l",
		keys: "mod+shift+l",
		enabled: true,
	},
	{
		id: "format.ordered-list",
		label: "Ordered List",
		category: "Format",
		defaultKeys: "mod+shift+o",
		keys: "mod+shift+o",
		enabled: true,
	},
	{
		id: "format.table",
		label: "Insert Table",
		category: "Format",
		defaultKeys: "mod+shift+y",
		keys: "mod+shift+y",
		enabled: true,
	},
]
